START
2016-04-05 21:10:26.847000
Initializing SVM: Loading Data....
loading train caffe features
Initializing SVM: Computing aggregated train data...
Progress aggregation. Business 100
2016-04-05 21:46:32.624000
Progress aggregation. Business 200
2016-04-05 22:05:19.145000
Progress aggregation. Business 300
2016-04-05 22:26:49.834000
Progress aggregation. Business 400
2016-04-05 22:42:37.476000
Progress aggregation. Business 500
2016-04-05 23:02:17.575000
Progress aggregation. Business 600
2016-04-05 23:20:17.411000
Progress aggregation. Business 700
2016-04-05 23:38:47.668000
Progress aggregation. Business 800
2016-04-05 23:58:58.437000
Progress aggregation. Business 900
2016-04-06 00:18:23.464000
Progress aggregation. Business 1000
2016-04-06 00:35:14.903000
Progress aggregation. Business 1100
2016-04-06 00:54:42.581000
Progress aggregation. Business 1200
2016-04-06 01:15:02.587000
Progress aggregation. Business 1300
2016-04-06 01:35:25.428000
Progress aggregation. Business 1400
2016-04-06 01:55:24.994000
Progress aggregation. Business 1500
2016-04-06 02:12:15.220000
Progress aggregation. Business 1600
2016-04-06 02:31:58.510000
Progress aggregation. Business 1700
2016-04-06 02:52:40.026000
Progress aggregation. Business 1800
2016-04-06 03:11:22.208000
Progress aggregation. Business 1900
2016-04-06 03:26:32.859000
Progress aggregation. Business 2000
2016-04-06 03:45:50.721000
Initializing SVM: Computating is done.
HALFWAY
Traceback (most recent call last):
  File "C:/Users/diede/PycharmProjects/DecisionTrees/MainSVM.py", line 9, in <module>
    svm = SVM_spreiding(loadAggData=False)
  File "C:\Users\diede\PycharmProjects\DecisionTrees\SVM_spreiding.py", line 46, in __init__
    print datetime.now()
AttributeError: 'module' object has no attribute 'now'

Process finished with exit code 1